"""CR-0008 acceptance G4/G9: rasters regenerated by the fixed generators
into a scratch directory must equal CR-0010's repaired rasters.

G4  pixel values identical (every pixel, full resolution)
G9  rasterio profile and tags(ns='IMAGE_STRUCTURE') identical; the
    default-namespace GROUSE_* tags are deliberately not compared

    python check_generator_parity.py --new <scratch dir> [--ref data/landfire]

Every *.tif in --new is compared with the file of the same name in
--ref. Exit status 1 on any difference.
"""
import argparse
import glob
import os
import sys

import numpy as np
import rasterio


def signature(src):
    p = dict(src.profile)
    p["crs"] = src.crs.to_wkt() if src.crs else None
    p["transform"] = tuple(src.transform)
    return p, src.tags(ns="IMAGE_STRUCTURE")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--new", required=True)
    ap.add_argument("--ref", default="data/landfire")
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    lines, failed = [], 0
    files = sorted(glob.glob(os.path.join(args.new, "**", "*.tif"),
                             recursive=True))
    if not files:
        sys.exit(f"no rasters under {args.new}")
    for new in files:
        name = os.path.basename(new)
        ref = os.path.join(args.ref, name)
        with rasterio.open(new) as a, rasterio.open(ref) as b:
            va, vb = a.read(1), b.read(1)
            diff = int((va != vb).sum()) if va.shape == vb.shape else -1
            sa, sb = signature(a), signature(b)
            prof = [k for k in set(sa[0]) | set(sb[0])
                    if sa[0].get(k) != sb[0].get(k)]
            struct = sa[1] == sb[1]
            cov = a.tags().get("GROUSE_COVERAGE")
        g4 = diff == 0
        g9 = not prof and struct
        failed += (not g4) + (not g9)
        lines.append(f"G4 {'PASS' if g4 else 'FAIL'}  {name:28s} "
                     f"differing px={diff}")
        lines.append(f"G9 {'PASS' if g9 else 'FAIL'}  {name:28s} "
                     f"profile diffs={prof or 'none'} "
                     f"IMAGE_STRUCTURE same={struct} "
                     f"(GROUSE_COVERAGE={cov})")
    lines.append(f"\n{len(files)} files, {failed} failure(s): "
                 + ("FAIL" if failed else "ALL PASS"))
    text = "\n".join(lines)
    print(text)
    if args.out:
        with open(args.out, "w") as f:
            f.write(text + "\n")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
